---
title: Comment la diversité spécifique du benthos varie-t-elle dans les rivières du Québec?

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Léanne Beauregard
    affiliation: a
  - name: Élyse Castilloux
    affiliation: a
  - name: Maude Roy
    affiliation: a
  - name: Erick-Daniel Vasquez
    affiliation: a
address:
  - code: a
    address: Univeristé de Sherbrooke, Département de Biologie, Street, City, State, Zip


# For footer text
lead_author_surname: Anonymous

abstract: |
  Dans le cadre du cours de Méthodes en écologie computationnelle (BIO500) nous avons analysé les données de 43 rivières, récoltées entre 2016 et 2021, sur la biodiversité benthique sur les rivières du Québec. Plus précisément, nous avons cherché à comprendre comment la diversité spécifique du benthos varie en fonction de la vitesse du courant, de la profondeur de la rivière et de la température de l’eau. Contrairement à ce que nous pensions, les résultats démontrent que seule la température de l’eau affecte significativement la richesse spécifique du benthos, mais que ce facteur n’explique qu’une infime partie de sa variance spatiale.


keywords:
  - Benthos
  - Rivière

## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle

bibliography: ref.bio500.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

output: rticles::pnas_article
---

Introduction 
========================================

Les cours d’eau regorgent de petits organismes qu’on ne perçoit pas toujours au premier abord, tel que les organismes benthiques. Le benthos représente l’ensemble des macro-invertébrés qui vivent dans le fond des cours d’eau et des lacs, comme des larves d’insectes, des crustacés et des vers. Il est important de faire un suivi des organismes benthiques, car ils peuvent être utilisés comme bio-indicateur, afin d’évaluer la santé du cours d’eau et qu’ils servent de nourriture pour un grand nombre d’animaux [@article{brysiewicz_characterisation_2022; @misc{melccfp_macroinvertebres_nodate]. Cette présente recherche cherche à caractériser comment la richesse spécifique varie d’une rivière à l’autre au Québec, à l’aide de trois questions principales, soit « comment la richesse spécifique du benthos varie en fonction de la vitesse du courant », « comment la richesse spécifique du benthos varie en fonction de la température de l’eau » et « comment la richesse spécifique du benthos varie en fonction de la profondeur de la rivière ». Nous pensons que ces trois facteurs devraient influencer la richesse spécifique du benthos, de manière positive ou négative.

Méthode 
========================================
Nous avons premièrement rassemblé et nettoyé les données récoltées par les équipes sur le terrain, pour créer une base de données commune où il sera possible d'ajouter les nouvelles données terrain prises à chaque année par la suite. Plus précisément, les données qui n’étaient pas présentes pour la majorité des rivières ou qui étaient doublées ont été éliminées et le format des données a également été homogénéisé. Ensuite, diverses requêtes ont été utilisées afin de déterminer comment les caractéristiques des rivières affectent la diversité spécifique du benthos. Trois régressions linéaires ont été faites, la première étant la richesse spécifique du benthos en fonction de la vitesse du courant, la deuxième la richesse spécifique du benthos en fonction de la profondeur de la rivière et la troisième la richesse spécifique du benthos en fonction de la température de l’eau. Afin de mieux visualiser ces résultats, trois différents tableaux ont été créés. Finalement, le tout a été rassemblé sous le format d’article à l’aide de Rmarkdown. L’ensemble de l’analyse et du nettoyage des données a été fait à l’aide du logiciel R studio (2024.12.0+467). Les package "dplyr", "readr", "DBI", "RSQLite", "janitor", "ggplot2", "rmarkdown" et "knitr" ont été utilisés. La totalité du code est disponible sur GitHub et rassemblée dans un pipeline target. Il faut noter que les logiciels Chat GPT(4.0) et co-pilot ont été utilisés afin d’aider à débugger les codes.

Résultats 
========================================
La richesse spécifique du benthos varie de façon positive avec la température de l’eau (pente = 0,5316, p=0,02946). Cependant, cette relation n’explique qu’une infime partie de la variation du benthos dans les différentes rivières, puisque le R2 est de 0,08632. Cette relation est visible dans le ##\\label{fig:plot1}.

FIGURE 1

Pour ce qui est des autres régressions, celle de la richesse spécifique en fonction de la rivière (p=0,293) et la vitesse du courant (p=0,532) ont respectivement des pentes de -0,2350 et 0,4067, mais ces relations ne sont pas significatives et ne peuvent donc pas être utilisées pour expliquer la variation spatiale du benthos. La relation entre la richesse spécifique et la vitesse du courant est illustrée dans le deuxième graphique ##\\label{fig:plot2}
, où la vitesse a été séparée en différentes catégories, afin de mieux illustrer comment elle varie. Puisque cette relation n’est pas significative, peu de variation est observée entre les différentes catégories, avec une diversité maximale lorsqu’il y a entre 0,4 et 0,6m de profondeur. Le ##\\label{fig:plot3}
quant à lui, représente comment la diversité spécifique est distribuée selon différentes classes de vitesse de courant : plus le pic d’une courbe est vers la droite et plus il est haut, plus la chance de retrouver une forte diversité benthique dans cette catégorie de vitesse est importante. 

FIGURE 2 ET 3

Discussion 
========================================
Selon nos résultats, la profondeur des rivières n’est pas un élément qui permet d’expliquer la différence dans la distribution spatiale du benthos, car la corrélation entre les deux variables n’est pas significative. Ce résultat nous étonne, car plusieurs études, dont une réalisée au Québec, semblent avoir trouvé un lien entre la profondeur et la différence en richesse spécifique [@article{brysiewicz_characterisation_2022; @article{tall_effects_2016]. La profondeur étant liée à d’autres paramètres comme la luminosité, la température et la disponibilité en oxygène, un de ces facteurs pourrait peut-être mieux expliquer la distribution spatiale du benthos.
Tel que mentionné dans les résultats, la vitesse du courant n’est pas significative non plus. Encore une fois, cela est contraire à ce que l’on s’attendait, puisque @article{barmuta_interaction_1990 et @article{brysiewicz_characterisation_2022 ont trouvé une relation significative entre ces variables. 
Ensuite, tel que nous l’avions prédit, la température de l’eau a un impact sur la richesse spécifique du benthos. Cependant, alors que dans les recherches précédentes la température était un facteur important expliquant l’évolution spatiale de la diversité benthique, selon notre analyse, elle n’explique qu’une très petite partie de cette dernière. @article{hawkins_channel_1997 et @article{bonacina_effects_2023 suggèrent que certains taxons ne peuvent tolérer des températures trop extrêmes : une régression linéaire simple ne représente peut-être pas la relation entre la température de l’eau et la richesse spécifique de la bonne manière, ce qui pourrait expliquer pourquoi elle explique peu la dispersion spatiale. Ainsi, dans une prochaine analyse, il serait pertinent de tenter d’expliquer la relation entre ces deux variables à l’aide d’une autre formule, par exemple la formule quadratique, afin de prendre en compte la possibilité que l’eau diminue la diversité benthique lorsqu’elle est trop froide et trop chaude. 
De manière semblable, les résultats non-significatifs sont peut-être expliqués par le fait que la distribution spatiale du benthos a été étudiée en un seul bloc. Il est possible que certains taxons soient plus affectés par un paramètre que d’autres, ou qu’ils soient affectés de manière contraire, ce qui aurait pu nuire à établir une corrélation significative entre la vitesse du courant ou la profondeur de la rivière et la richesse spécifique.
Finalement, il pourrait être intéressant faire des analyses multivariées afin de tenter d’avoir des résultats plus significatifs. Soit en prenant en compte plusieurs des variables étudiées dans cette présente analyse, soit en prenant en compte d’autres facteurs qui n’étaient pas présents dans les données récoltées, tel que le niveau d’oxygénation de l’eau ou sa concentration en nitrogène, qui sont important pour expliquer la diversité du benthos @article{brysiewicz_characterisation_2022. 


References {#references .unnumbered}
========================================



<!-- Leave these lines as they are at the end of your .Rmd file to ensure placement of methods & acknowledgements sections before the references-->
\showmatmethods
\showacknow
\pnasbreak
